### ISSUE TITLE
No spacing between heading and code block

### ISSUE THREAD

**Issue by ncfavier** [plt-amy/1lab#363]
![](https://f.monade.li/5AOhhh.png)

**Comment by plt-amy** [comment]
```css
h1 + .Agda, h2 + .Agda, h3 + .Agda, h4 + .Agda, h5 + .Agda, h6 + .Agda {
  margin-block-start: 1em;
}
```
adding this to `code.scss` should fix it; can you try it?
